# Created by Jekyll Writer
title: My Blog
author: Diao
description: Memo tech
permalink: '/:year/:month/:day/:title/'
paginate: 10
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jekyllwriter
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /blog
theme: jekyll-theme-cayman
